robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 10, i: 0.1, d: 0}
  
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 10, i: 0.1, d: 0}

  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 10, i: 0.1, d: 0}
  
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 10, i: 0.1, d: 0}

  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 10, i: 0.1, d: 0}