<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">

    <link name="base_link" />

    <xacro:include filename="$(find rover_description)/urdf/rover_movement/rover_movement.xacro"/>
    <xacro:include filename="$(find rover_description)/urdf/rover_manipulator/rover_manipulator.xacro"/>

    <joint name="base_link_to_chassis" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 ${-chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <joint name="base_link_to_manipulator_link_joint" type="fixed">
        <origin xyz="0 0.23 0" rpy="0 0 ${PI}"/>
        <parent link="base_link"/>
        <child link="manipulator_link"/>
    </joint>
</robot>