<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
    <link name="base_link" />

    <xacro:include filename="$(find rover_description)/urdf/rover_movement/rover_movement.xacro"/>

    <joint name="base_link_to_chassis" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 ${-chassis_height/2}" rpy="0 0 0"/>
    </joint>
</robot>